name: Deploy infrastructure

on:
  push:
    branches:
    - master

permissions:
  id-token: write
  contents: read

env:
  LOCATION: westeurope
      
jobs: 
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Deploy infrastructure
      run: |
          VERSION=`date '+%Y.%m%d.%H%M'`
          az deployment sub create \
            --name "bicep-github-actions-${VERSION}" \
            --location $LOCATION \
            --template-file main.bicep \
            --parameters resourceGroupName=bicep-github-actions-live
            
          