name: Whatif

on:
  pull_request:
    types: 
    - opened
    - reopened
    - edited
    branches:
    - master 
  
permissions:
  id-token: write
  contents: read
  pull-requests: write
  
env:
  LOCATION: westeurope

jobs:
  evaluate-infrastructure-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Bicep Lint
      run: |
        az bicep lint --file main.bicep
        
    - name: Bicep what-if
      id: whatif
      run: |
          WHATIF=$(az deployment sub what-if \
            --name bicep-github-actions-${{ github.run_id }} \
            --location $LOCATION \
            --template-file main.bicep \
            --parameters resourceGroupName=bicep-github-actions-live)
          
          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Whatif Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "$WHATIF" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Push Whatif Output to PR
      uses: actions/github-script@v6
      env:
        SUMMARY: "${{ steps.whatif.outputs.whatif }}"
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY}`;
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
            })
            
  